name: generate plantuml

on: push

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    permissions: write-all
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: svg
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
      - id: upload-folder
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: svg
          destination: 'mangata-diagrams'