name: generate plantuml

on: push

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: svg
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: google-github-actions/auth@v2
        id: auth
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      
      - name: Delete Existing Files in Bucket
        run: gsutil -m rm -a gs://mangata-diagrams/**
      - id: upload-folder
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: svg
          destination: 'mangata-diagrams'
          headers: |-
            cache-control: 'no-store, max-age=0'
